# Generated by Django 5.0.6 on 2024-06-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
